version: '3.8'

services:
  dotnet_app:
    build: ./SOE
    container_name: soe_dotnet_app
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=EmotionalMessenger;Username=postgres;Password=12345
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    ports:
      - "5000:5000"
    platform: linux/amd64
  postgres:
    build: ./postgres
    container_name: soe_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: EmotionalMessenger
    platform: linux/amd64
  redis:
    image: redis:7-alpine
    container_name: soe_redis
    ports:
      - "6379:6379"
    platform: linux/amd64

  emotion_service:
    build: ./emotion_service
    container_name: emotion_service
    ports:
      - "5001:5001"
    platform: linux/amd64


  