version: '3.8'

services:
  dotnet_app:
    build: ./SOE
    container_name: soe_dotnet_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=EmotionalMessenger;Username=postgres;Password=12345
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    ports:
      - "5000:5000"
  postgres:
    build: ./postgres
    container_name: soe_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: EmotionalMessenger
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: soe_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  emotion_service:
    build: ./emotion_service
    container_name: emotion_service
    restart: always
    ports:
      - "5001:5001"


  